<?php
header('Cache-Control: no-store, max-age=0');
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' blob:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Galeria • M.T.O</title>
<style>
:root{font:16px/1.5 system-ui,sans-serif;color:#17191b;background:#f7f7f5}*{box-sizing:border-box}body{margin:0}header{background:#111315;color:white;padding:20px max(20px,calc((100vw - 1100px)/2));display:flex;align-items:center;justify-content:space-between;gap:20px}header strong{font-size:24px}a{color:inherit;text-underline-offset:4px}main{max-width:1100px;margin:40px auto;padding:0 20px}h1{font-size:32px;letter-spacing:-.04em;margin:0 0 12px}h2{font-size:21px;margin:0 0 16px}p{margin:0 0 20px}.panel{background:white;border:1px solid #d1d2d0;border-radius:12px;padding:24px;margin-bottom:24px}.login{max-width:500px;margin:48px auto}label{display:block;font-weight:600;margin:16px 0 8px}input{width:100%;padding:12px;min-height:48px;font:inherit;border:1px solid #74777a;border-radius:8px}button,.button{font:700 15px/1.4 system-ui;min-height:48px;padding:12px 20px;border:1px solid transparent;border-radius:10px;background:#ffc629;color:#111315;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}button:hover{background:#e9a900}button:disabled{opacity:.6;cursor:wait}.secondary{background:white;border-color:#d1d2d0}.secondary:hover{background:#eee}.danger{background:white;color:#a51e1e;border-color:#d1d2d0}button:focus-visible,input:focus-visible,a:focus-visible{outline:3px solid #3957bd;outline-offset:3px}[hidden]{display:none!important}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}.small{font-size:14px;color:#414447}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:20px}.card{margin:0;background:white;border:1px solid #d1d2d0;border-radius:12px;overflow:hidden}.card img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.card figcaption{padding:16px;overflow-wrap:anywhere}.card button{margin:0 16px 16px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}#message{padding:16px;border-left:4px solid #3957bd;background:white;border-radius:8px;margin-bottom:24px;overflow-wrap:anywhere}#message.error{border-color:#d83a3a}#preview{display:block;max-width:100%;height:180px;object-fit:contain;margin-top:16px;border-radius:8px}.upload-layout{display:grid;grid-template-columns:1fr;gap:24px}@media(min-width:768px){.upload-layout{grid-template-columns:1fr 1fr}}
</style></head><body><header><strong>M.T.O</strong><a href="index.html" target="_blank" rel="noopener">Ver site ↗</a></header><main>
<div id="message" role="status" aria-live="polite">Carregando…</div>
<section class="panel login" id="login-panel" hidden><h1 id="login-title">Gerenciar galeria</h1><p id="login-description">Entre para publicar e excluir fotos dos seus serviços.</p><form id="login-form"><div id="setup-fields" hidden><label for="setup-key">Chave do primeiro acesso</label><input id="setup-key" type="password" autocomplete="off"><p class="small">Use a chave entregue junto com os arquivos do site. Ela funciona somente no primeiro acesso.</p></div><label for="password">Senha</label><input id="password" type="password" required maxlength="128" autocomplete="current-password"><div id="confirm-fields" hidden><label for="confirm">Repita a senha</label><input id="confirm" type="password" maxlength="128" autocomplete="new-password"></div><div class="actions"><button type="submit" id="login-button">Entrar</button></div></form></section>
<section id="manager" hidden><div class="top"><div><h1>Fotos dos seus serviços</h1><p>Adicione uma foto e ela aparecerá na galeria do site.</p></div><button type="button" class="secondary" id="logout">Sair</button></div><section class="panel"><h2>Publicar uma foto</h2><form id="upload-form"><div class="upload-layout"><div><label for="photo">Escolha a foto</label><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" required><p class="small">JPG, PNG ou WebP. Até 8 MB e 24 megapixels por foto. Limite de 60 fotos.</p><img id="preview" alt="Prévia da foto escolhida" hidden></div><div><label for="description">Qual serviço aparece na foto?</label><input id="description" type="text" required maxlength="160" placeholder="Ex.: Instalação de ventilador de teto"><p class="small">Essa descrição também ajuda quem usa leitor de tela.</p><div class="actions"><button type="submit" id="upload-button">Publicar foto</button></div></div></div></form></section><div class="top"><h2 id="photo-count">Fotos publicadas</h2></div><p id="empty" hidden>Ainda não há fotos enviadas. A galeria do site continua exibindo as imagens iniciais.</p><div class="grid" id="photos"></div></section>
</main><script>
let session, previewURL;
const $=id=>document.getElementById(id);
function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').classList.toggle('error',error);}
async function api(action,data){const options={credentials:'same-origin',cache:'no-store'};if(data){data.set('csrf',session.csrf);options.method='POST';options.body=data;}const response=await fetch('galeria-api.php?action='+action,options);let result;try{result=await response.json();}catch{throw new Error('O servidor não respondeu. Confirme se o PHP está ativo na hospedagem.');}if(!response.ok)throw new Error(result.error||'Não foi possível concluir.');return result;}
async function refresh(){session=await api('session');$('login-panel').hidden=session.authenticated;$('manager').hidden=!session.authenticated;$('setup-fields').hidden=session.configured;$('confirm-fields').hidden=session.configured;$('password').minLength=session.configured?1:12;$('password').autocomplete=session.configured?'current-password':'new-password';$('login-title').textContent=session.configured?'Gerenciar galeria':'Crie seu acesso';$('login-description').textContent=session.configured?'Entre para publicar e excluir fotos dos seus serviços.':'Defina uma senha de pelo menos 12 caracteres para proteger sua galeria.';$('login-button').textContent=session.configured?'Entrar':'Criar acesso';if(session.authenticated)await loadPhotos();}
async function loadPhotos(){const data=await api('list');$('photos').replaceChildren();$('empty').hidden=data.photos.length!==0;$('photo-count').textContent='Fotos publicadas ('+data.photos.length+'/60)';for(const photo of data.photos){const card=document.createElement('figure');card.className='card';const img=new Image();img.src=photo.url;img.alt=photo.alt;img.loading='lazy';const caption=document.createElement('figcaption');caption.textContent=photo.alt;const remove=document.createElement('button');remove.className='danger';remove.type='button';remove.textContent='Excluir foto';remove.setAttribute('aria-label','Excluir: '+photo.alt);remove.onclick=async()=>{if(!confirm('Excluir esta foto da galeria?'))return;remove.disabled=true;try{const form=new FormData();form.set('id',photo.id);await api('delete',form);await loadPhotos();message('Foto excluída.');}catch(e){message(e.message,true);remove.disabled=false;}};card.append(img,caption,remove);$('photos').append(card);}}
$('login-form').onsubmit=async e=>{e.preventDefault();if(!session.configured&&$('password').value!==$('confirm').value){message('As senhas precisam ser iguais.',true);return;}$('login-button').disabled=true;try{const form=new FormData();form.set('password',$('password').value);form.set('key',$('setup-key').value);await api(session.configured?'login':'setup',form);$('login-form').reset();await refresh();message('Acesso liberado.');}catch(err){message(err.message,true);}finally{$('login-button').disabled=false;}};
$('photo').onchange=()=>{if(previewURL)URL.revokeObjectURL(previewURL);const file=$('photo').files[0];$('preview').hidden=!file;if(file){previewURL=URL.createObjectURL(file);$('preview').src=previewURL;}};
$('upload-form').onsubmit=async e=>{e.preventDefault();const file=$('photo').files[0];if(!file)return;if(file.size>8*1024*1024){message('A foto deve ter até 8 MB.',true);return;}$('upload-button').disabled=true;message('Enviando foto…');try{const form=new FormData();form.set('photo',file);form.set('description',$('description').value);await api('upload',form);$('upload-form').reset();$('preview').hidden=true;if(previewURL)URL.revokeObjectURL(previewURL);await loadPhotos();message('Foto publicada. Ela já está disponível no site.');}catch(err){message(err.message,true);}finally{$('upload-button').disabled=false;}};
$('logout').onclick=async()=>{try{await api('logout',new FormData());await refresh();message('Você saiu da área administrativa.');}catch(e){message(e.message,true);}};
const key=new URLSearchParams(location.hash.slice(1)).get('configurar');if(key){$('setup-key').value=key;history.replaceState(null,'',location.pathname);}
refresh().then(()=>message('')).catch(e=>message(e.message,true));
</script></body></html>
